- redhat/patches/0002-validate-release-patch.txt
Small patch file to fix the current job failing, ref: https://github.com/sigstore/cosign/pull/3169
> add patch file for validate-release job

- redhat/overlays/Dockerfile
All Red Hat products produced via RHTAP are required to use the Red Hat "enterprise contract" integration test, found here: https://github.com/redhat-appstudio/build-definitions/blob/main/pipelines/enterprise-contract-redhat.yaml.
This commit adds labels to the Dockerfile, overriding certain inherited labels. In some cases, the enterprise contract disallows labels to be inherited. This should resolve those failing checks.
I've also updated the run image to use ubi9 as a base image, with the latest SHA.
> Adds labels to conform to RH enterprise contract

- .tekton/cosign-pull-request.yaml
- .tekton/cosign-push.yaml
This should satisfy enterprise contract checks for RHTAP.
> Use hermetic builds and prefetched input

- redhat/overlays/Dockerfile
These labels need to be set for RHTAP. But probably only for the run image and not for the build image. :)
> Move Dockerfile labels to the run image

- redhat/release/update-to-head.sh
The overall strategy with our sync script is:
- Maintain a branch with overlays and modifications to the upstream (`main` and `midstream-vX.Y.Z`)
- Maintain a branch which mirrors upstream with our overlays and modifications applied (`release-next` and `redhat-vX.Y.Z`). This includes the rhtap `.tekton` folder, which needs to be treated specially because rhtap cannot support writing these to a branch other than the one that is to be built by rhtap, i.e. the `redhat-vX.Y.Z`  branch.
There is currently also a `release-next-ci` and `redhat-vX.Y.Z-ci` branch which is applied via the PR which is created from the update-to-head.sh script.
At the moment, we force push both the `redhat-vX.Y.Z` and `redhat-vX.Y.Z-ci` branches. But I don’t think we need to actually force push the release branch …
> chore: don't force push the release branch

- redhat/overlays/Dockerfile
It completely slipped my mind that cosign was used on cluster. This should address that issue.
> Renamed linux cosign binary to be just "cosign".

- Dockerfile.client-server-cg.rh
- Dockerfile.client-server-re.rh
This pr removes the web server aspects of the cli binary images related to: https://github.com/securesign/secure-sign-operator/pull/227
> client-server-changes

- Dockerfile.client-server-re.rh
Updates `ec` to the latest image for release consideration.
> chore: update ec image coordinates/sha

- Dockerfile.cosign.rh
Instead of moving the binary to be named `cosign`, this change modifies the Dockerfile so that the binary is copied to the new, shortened name, leaving the original, more descriptive name. This simplifies its usage in other images, such as the CLI download image where the original name is desired.
> docker: keep cosign-linux-amd64 - cp instead of mv

- Dockerfile.cosign.rh
Ensures that there is an executable `/usr/local/bin/cosign` as well as a gzipped version of the arch-named binary.
> chore(docker): ensure an executable cosign

- .tekton/client-server-cg-pull-request.yaml
- .tekton/client-server-cg-push.yaml
- .tekton/client-server-re-pull-request.yaml
- .tekton/client-server-re-push.yaml
- Dockerfile.client-server-cg.rh
- Dockerfile.client-server-re.rh
This attempts to make the CLI server builds hermetic by removing the use of `oc image extract`. This was the approach used in our TP2 release because when the `ec` binary was added to `cosign`, `gitsign` and `rekor-cli` the source build exceeded the pipeline results size limit and caused build failures. We have since also changed how the download image works and it is now separated into two images with the CLI binaries, which are used as data for a generic HTTP server.
All of this is to say that we don't need `oc image extract` now because the whole thing has been split into two images and should not trigger size limits on pipeline results.
> feat: make CLI server builds hermetic

- Dockerfile.client-server-re.rh
Contains ec v0.2.3 built on git sha
c21271a0ee838b676e0cdd955d752cbc8630a347 in the
enterprise-contract/ec-cli repo.
Note that the previous image was specified using an image tag, not the image digest, so that's why the diff looks like it does.
> Update ec build sha cli image

- Build.mak
- Dockerfile.cosign.rh
Jira: https://issues.redhat.com/browse/SECURESIGN-777
This is part one of this ticket this needs to be merged before pt2 can be, adds the .exe extension to the cosign binary for windows
> fix: add-exe-extension-to-cosign pt1

- Dockerfile.client-server-re.rh
This is the same image that is available at `registry.redhat.io/rhtas/ec-rhel9:0.4-e53a8aa`.
> Update ec-cli image to a fresh v0.4 build

- Dockerfile.client-server-re.rh
The ec version is `v0.4.79+redhat` built on sha 9faa387. The image is identical to `registry.redhat.io/rhtas/ec-rhel9:0.4-1718293643`.
Should resolve SECURESIGN-1054. See also https://github.com/enterprise-contract/ec-cli/pull/1697 .
> Bump ec-cli reference to latest digest

- internal/ui/index.go
- release-plans/gamma/ReleasePlan.yaml
The license check CI was failing. This should make it pass.
Done like this:
```
podman run -it -v ${PWD}:/src ghcr.io/google/addlicense \
-l apache -c 'The Sigstore Authors' -ignore "third_party/**" -v *
```
See also license-check in .github/workflows/tests.yaml.
> Add license preamble to two files

- .github/workflows/kind-e2e-insecure-registry.yaml
- .github/workflows/whitespace.yaml
- Build.mak
- Dockerfile.cosign.rh
The konflux build does not include all the necessary metadata for the `cosign version` command. This change should ensure that the command produces the correct information.
`cosign version` output for a local build now looks like this
```
podman run localhost/cosign-test:latest cosign version
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
______   ______        _______. __    _______ .__   __.
/      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
\______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI …
```
> fix(SECURESIGN-1179): include version metadata

- Dockerfile.client-server-re.rh
The newer ec-cli image contains the following ec version:
```
Version            v0.4.82+redhat
Source ID          e513427c2a98e2d6b0ef6c95ed5a83af741c4276
Change date        2024-07-01 15:27:07 +0000 UTC (2 weeks ago)
```
[Changes](https://github.com/enterprise-contract/ec-cli/compare/9faa38736ba8af53bcfef760b2d8359aa8e91cf1...e513427c2a98e2d6b0ef6c95ed5a83af741c4276).
There are no functional changes. The significant change is that one dependency was upgraded.
Note: This kind of commit should be created automatically once we have Konflux nudging configured correctly for the ec-cli component, see [EC-691](https://issues.redhat.com/browse/EC-691).
> chore(deps): Update ec cli digest to newer version

- Dockerfile.clients.rh
The Konflux team has made changes to the build-source-image task, which previously failed when adding more than just cosign, gitsign and rekor-cli to the image. When we added ec to it, the task began to fail due to an overly large results string, which Konflux could not handle. That limitation in Konflux has been eliminated.
The change in this commit is to create a single CLI download image, which can be used by the operator, instead of the multiple currently in place. Once this change is committed on the main branch, a new component can be created in Konflux to test the build. If it is successful, we can remove the following components from the `cli` Application in Konflux, and subsequently remove those Dockerfiles from this repo.
The following components can be removed after this build …
> chore: create a single CLI download image

- go.mod
- go.sum
Addresses [CVE-2024-41110](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-41110)
Cherry pick of https://github.com/sigstore/cosign/pull/3823
> chore(deps): bump github.com/docker/docker (#3823)

- Dockerfile.client-server-re.rh
- Dockerfile.clients.rh
Now that the EC image goes through a proper release process, let's use that instead of using the latest built image.
> Use released version of EC image

- Dockerfile.client-server-re.rh
- Dockerfile.clients.rh
The v0.5 release branch was split from main branch recently. This is the latest image built from that branch.
```
$ podman run --rm registry.redhat.io/rhtas/ec-rhel9:0.5 version
Version            v0.5.149+redhat
Source ID          76de2bf70f367f6d874cb77dde3828000853eb6a
Change date        2024-09-12 15:59:32 +0000 UTC (5 hours ago)
...
```
See also:
https://github.com/enterprise-contract/ec-cli/compare/release-v0.4...76de2bf70f
Ref: https://issues.redhat.com/browse/EC-819
> Upgrade Enterprise Contract from v0.4 to v0.5

- Dockerfile.clients.rh
```
➜  Downloads ./cosign-amd64 version   
______   ______        _______. __    _______ .__   __.
/      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
\______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.
GitVersion:    a3ec4904
GitCommit:     a3ec4904ac89b617ecb95e0b13be90cc6b7ede1c
GitTreeState:  clean
BuildDate:     2024-10-03T08:16:29Z
GoVersion:     go1.22.5 (Red Hat 1.22.5-1.el9)
Compiler:      gc
Platform:      linux/amd64
➜  Downloads ./rekor-cli-amd64 version
____    _____   _  __   ___    ____             ____   _ …
```
> fix: Updating the cosign and rekor-cli binarys with clean versions
