securesign/cosign

redhat/overlays/cosign/Dockerfile

Small patch to fix cosign image in image-factory

fix cosign image

---

redhat/patches/0001-tests-yaml.patch

This added patch enables the license checker to pass.

chore: add patchfile to deal with license checks

---

redhat/overlays/Dockerfile

The image in the image factory failed with the new change without this line, this pr is just a small change to fix this.

small change to docker file

---

.tekton/cosign-pull-request.yaml
.tekton/cosign-push.yaml

Required for RHTAP Enterprise Contract

chore: enable hermetic builds and prefetched dependencies

---

redhat/overlays/Dockerfile

deps(ubi-minimal): bump to latest sha256

---

redhat/overlays/Dockerfile

The cachi2 pipelinerun task in RHTAP modifies the Dockerfile to inject the cached dependency information into the build. This causes the git version - which is injected into the CLI version output - to include a `-dirty` suffix.
The modification in this commit stashes those changes, and then gets the git hash, storing it in the `GIT_VERSION` environment variable, then pops those changes back off of the stash and runs the build as before.
The commit also contains some optimizations so that most of the `RUN` commands are consolidated into one.

rhtap: update Dockerfile to get a clean git hash

---

.tekton/cosign-cli-2-2-pull-request.yaml
.tekton/cosign-cli-2-2-push.yaml

Adding Source Container build for cosign cli.

[SECURESIGN-252] | Enabling build-source-image for cli.

---

.tekton/cosign-cli-2-2-pull-request.yaml
.tekton/cosign-cli-2-2-push.yaml

Enabling Prefetch and Hermetic builds for cli.

[SECURESIGN-254] [SECURESIGN-253] | Enabling prefetch and hermetic build for cli.

---

.github/workflows/cronjobs.yaml

Small pr to update check-image-version job

Update cron job

---

.tekton/cosign-cli-2-2-pull-request.yaml
.tekton/cosign-cli-2-2-push.yaml
.tekton/cosign-unit-test.yaml

PR to re-add go unit tests to cosign

SECURESIGN-185 | Add tests to all pipelines

---

release-plans/gamma/ReleasePlan.yaml

release plan for gamma cli

---

.tekton/client-server-pull-request.yaml
.tekton/client-server-push.yaml
Dockerfile.client-server.rh

Adds the client server image, with its pipelines

add-client-server-image

---

.tekton/cosign-pull-request.yaml
.tekton/cosign-push.yaml
.tekton/cosign-unit-test.yaml

Small pr to fix the unit tests running in Konflux

fix: fix unit tests

---

Dockerfile.client-server-cg.rh
Dockerfile.client-server-re.rh
Dockerfile.cosign.rh

Test pr to trigger builds please ignore

Test pr to trigger builds

---

Dockerfile.client-server-cg.rh
Dockerfile.client-server-re.rh
Dockerfile.cosign.rh

testing pipelines

---

Dockerfile.client-server-cg.rh
Dockerfile.client-server-re.rh
Dockerfile.cosign.rh

generate builds

---

Dockerfile.client-server-cg.rh
Dockerfile.client-server-re.rh

Small pr to update client server images

chore: update-client-server-images

---

.github/workflows/trigger-konflux-build.yaml
.tekton/client-server-cg-pull-request.yaml
.tekton/client-server-re-pull-request.yaml

Adding this action: https://github.com/securesign/actions/blob/main/.github/workflows/trigger-konflux-build.yaml

add-trigger-action

---

.tekton/client-server-cg-pull-request.yaml
.tekton/client-server-cg-push.yaml
.tekton/client-server-re-pull-request.yaml
.tekton/client-server-re-push.yaml
.tekton/cosign-pull-request.yaml
.tekton/cosign-push.yaml

Relates to https://redhat-internal.slack.com/archives/C05M2GGKU7Q/p1715707450761549
/cc @lance

bumping deprecated image check to v0.4 for cosign

---

.tekton/client-server-f-pull-request.yaml
.tekton/client-server-f-push.yaml

Enable hermetic builds, build source image and prefetch, changed url to securesign, update cel expressions

Enable hermetic builds, build source image and prefetch, changed url to securesign, update cel expressions

---

.tekton/client-server-pull-request.yaml
.tekton/client-server-push.yaml

Whatever that means for this kind of image <shrug>

chore(pipeline): enable hermetic builds
